
BC_INTFAS = 8
BC_INTFA = 9
BC_STRINGS = 10
BC_RTNS = 11
BC_RTN = 12

BC_INTFA_STATE = 0
BC_INTFA_FINAL_STATE = 1
BC_INTFA_TRANSITION = 2
BC_INTFA_TRANSITION_RANGE = 3

BC_STRING = 4

BC_RTN_NAME = 5
BC_RTN_STATE = 6
BC_RTN_TRANSITION_TERMINAL = 7
BC_RTN_TRANSITION_NONTERM = 8
BC_RTN_DECISION = 9

